// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShop.Data;

namespace TechShop.Migrations
{
    [DbContext(typeof(TechDbContext))]
    [Migration("20200313115949_CreateProductView")]
    partial class CreateProductView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechShop.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("TechShop.Models.Breadcrumb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breadcrumb");
                });

            modelBuilder.Entity("TechShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Lft")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Rgt")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 0,
                            Lft = 1,
                            Name = "Categories",
                            ParentId = 0,
                            Rgt = 38,
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Lft = 2,
                            Name = "Computers and laptops",
                            ParentId = 1,
                            Rgt = 7,
                            Url = "computers-and-laptops"
                        },
                        new
                        {
                            Id = 3,
                            Level = 2,
                            Lft = 3,
                            Name = "Laptops",
                            ParentId = 2,
                            Rgt = 6,
                            Url = "laptops"
                        },
                        new
                        {
                            Id = 4,
                            Level = 3,
                            Lft = 4,
                            Name = "All Laptops",
                            ParentId = 3,
                            Rgt = 5,
                            Url = "all-laptops"
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Lft = 8,
                            Name = "Photo and video",
                            ParentId = 1,
                            Rgt = 17,
                            Url = "photo-and-video"
                        },
                        new
                        {
                            Id = 6,
                            Level = 2,
                            Lft = 9,
                            Name = "Cameras",
                            ParentId = 5,
                            Rgt = 10,
                            Url = "cameras"
                        },
                        new
                        {
                            Id = 7,
                            Level = 2,
                            Lft = 11,
                            Name = "Lenses, optics, flashes",
                            ParentId = 5,
                            Rgt = 16,
                            Url = "lenses-optics-flashes"
                        },
                        new
                        {
                            Id = 8,
                            Level = 3,
                            Lft = 12,
                            Name = "Lenses",
                            ParentId = 7,
                            Rgt = 15,
                            Url = "lenses"
                        },
                        new
                        {
                            Id = 9,
                            Level = 1,
                            Lft = 18,
                            Name = "TVs, audio, video",
                            ParentId = 1,
                            Rgt = 27,
                            Url = "tvs-audio-video"
                        },
                        new
                        {
                            Id = 10,
                            Level = 2,
                            Lft = 19,
                            Name = "TVs",
                            ParentId = 9,
                            Rgt = 26,
                            Url = "tvs"
                        },
                        new
                        {
                            Id = 11,
                            Level = 3,
                            Lft = 20,
                            Name = "All TVs",
                            ParentId = 10,
                            Rgt = 21,
                            Url = "all-tvs"
                        },
                        new
                        {
                            Id = 12,
                            Level = 3,
                            Lft = 22,
                            Name = "Smart-TVs",
                            ParentId = 10,
                            Rgt = 23,
                            Url = "smart-tvs"
                        },
                        new
                        {
                            Id = 13,
                            Level = 3,
                            Lft = 24,
                            Name = "OLED TVs",
                            ParentId = 10,
                            Rgt = 25,
                            Url = "oled-tvs"
                        },
                        new
                        {
                            Id = 14,
                            Level = 1,
                            Lft = 28,
                            Name = "Smartphones and gadgets",
                            ParentId = 1,
                            Rgt = 37,
                            Url = "smartphones-and-gadgets"
                        },
                        new
                        {
                            Id = 15,
                            Level = 2,
                            Lft = 29,
                            Name = "Smartphones",
                            ParentId = 14,
                            Rgt = 32,
                            Url = "smartphones"
                        },
                        new
                        {
                            Id = 16,
                            Level = 3,
                            Lft = 30,
                            Name = "All Smartphones",
                            ParentId = 15,
                            Rgt = 31,
                            Url = "all-smartphones"
                        },
                        new
                        {
                            Id = 17,
                            Level = 2,
                            Lft = 33,
                            Name = "Tablets",
                            ParentId = 14,
                            Rgt = 36,
                            Url = "tablets"
                        },
                        new
                        {
                            Id = 18,
                            Level = 3,
                            Lft = 34,
                            Name = "All Tablets",
                            ParentId = 17,
                            Rgt = 35,
                            Url = "all-tablets"
                        });
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("TechShop.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.HasOne("TechShop.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.Discount", b =>
                {
                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.HasOne("TechShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
