// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShop.Data;

namespace TechShop.Migrations
{
    [DbContext(typeof(TechDbContext))]
    [Migration("20200318133623_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechShop.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Epson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("TechShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 0,
                            Name = "Categories",
                            ParentId = 0,
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Name = "Computers and laptops",
                            ParentId = 1,
                            Url = "computers-and-laptops"
                        },
                        new
                        {
                            Id = 3,
                            Level = 2,
                            Name = "Laptops",
                            ParentId = 2,
                            Url = "laptops"
                        },
                        new
                        {
                            Id = 4,
                            Level = 3,
                            Name = "All Laptops",
                            ParentId = 3,
                            Url = "all-laptops"
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Name = "Photo and video",
                            ParentId = 1,
                            Url = "photo-and-video"
                        },
                        new
                        {
                            Id = 6,
                            Level = 2,
                            Name = "Cameras",
                            ParentId = 5,
                            Url = "cameras"
                        },
                        new
                        {
                            Id = 7,
                            Level = 2,
                            Name = "Lenses, optics, flashes",
                            ParentId = 5,
                            Url = "lenses-optics-flashes"
                        },
                        new
                        {
                            Id = 8,
                            Level = 3,
                            Name = "Lenses",
                            ParentId = 7,
                            Url = "lenses"
                        },
                        new
                        {
                            Id = 9,
                            Level = 1,
                            Name = "TVs, audio, video",
                            ParentId = 1,
                            Url = "tvs-audio-video"
                        },
                        new
                        {
                            Id = 10,
                            Level = 2,
                            Name = "TVs",
                            ParentId = 9,
                            Url = "tvs"
                        },
                        new
                        {
                            Id = 11,
                            Level = 3,
                            Name = "All TVs",
                            ParentId = 10,
                            Url = "all-tvs"
                        },
                        new
                        {
                            Id = 12,
                            Level = 3,
                            Name = "Smart-TVs",
                            ParentId = 10,
                            Url = "smart-tvs"
                        },
                        new
                        {
                            Id = 13,
                            Level = 3,
                            Name = "OLED TVs",
                            ParentId = 10,
                            Url = "oled-tvs"
                        },
                        new
                        {
                            Id = 14,
                            Level = 1,
                            Name = "Smartphones and gadgets",
                            ParentId = 1,
                            Url = "smartphones-and-gadgets"
                        },
                        new
                        {
                            Id = 15,
                            Level = 2,
                            Name = "Smartphones",
                            ParentId = 14,
                            Url = "smartphones"
                        },
                        new
                        {
                            Id = 16,
                            Level = 3,
                            Name = "All Smartphones",
                            ParentId = 15,
                            Url = "all-smartphones"
                        },
                        new
                        {
                            Id = 17,
                            Level = 2,
                            Name = "Tablets",
                            ParentId = 14,
                            Url = "tablets"
                        },
                        new
                        {
                            Id = 18,
                            Level = 3,
                            Name = "All Tablets",
                            ParentId = 17,
                            Url = "all-tablets"
                        });
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoryId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 18,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("TechShop.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(2,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "New Year Sale",
                            EndDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15m,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "First Year of Shop Opening",
                            EndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 5m,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Special Laptops Sale",
                            EndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 5m,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TechShop.Models.PAVPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("PValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PValueId");

                    b.HasIndex("PAttributeId", "PValueId")
                        .IsUnique();

                    b.ToTable("PAVPair");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PAttributeId = 1,
                            PValueId = 1
                        },
                        new
                        {
                            Id = 2,
                            PAttributeId = 1,
                            PValueId = 2
                        },
                        new
                        {
                            Id = 3,
                            PAttributeId = 1,
                            PValueId = 3
                        },
                        new
                        {
                            Id = 4,
                            PAttributeId = 1,
                            PValueId = 4
                        },
                        new
                        {
                            Id = 5,
                            PAttributeId = 1,
                            PValueId = 5
                        },
                        new
                        {
                            Id = 6,
                            PAttributeId = 1,
                            PValueId = 6
                        },
                        new
                        {
                            Id = 7,
                            PAttributeId = 1,
                            PValueId = 7
                        },
                        new
                        {
                            Id = 8,
                            PAttributeId = 1,
                            PValueId = 8
                        },
                        new
                        {
                            Id = 9,
                            PAttributeId = 1,
                            PValueId = 9
                        },
                        new
                        {
                            Id = 10,
                            PAttributeId = 2,
                            PValueId = 10
                        },
                        new
                        {
                            Id = 11,
                            PAttributeId = 2,
                            PValueId = 11
                        },
                        new
                        {
                            Id = 12,
                            PAttributeId = 2,
                            PValueId = 12
                        },
                        new
                        {
                            Id = 13,
                            PAttributeId = 2,
                            PValueId = 13
                        },
                        new
                        {
                            Id = 14,
                            PAttributeId = 2,
                            PValueId = 14
                        },
                        new
                        {
                            Id = 15,
                            PAttributeId = 2,
                            PValueId = 15
                        },
                        new
                        {
                            Id = 16,
                            PAttributeId = 3,
                            PValueId = 16
                        },
                        new
                        {
                            Id = 17,
                            PAttributeId = 3,
                            PValueId = 17
                        },
                        new
                        {
                            Id = 18,
                            PAttributeId = 3,
                            PValueId = 18
                        },
                        new
                        {
                            Id = 19,
                            PAttributeId = 3,
                            PValueId = 19
                        },
                        new
                        {
                            Id = 20,
                            PAttributeId = 3,
                            PValueId = 20
                        },
                        new
                        {
                            Id = 21,
                            PAttributeId = 4,
                            PValueId = 21
                        },
                        new
                        {
                            Id = 22,
                            PAttributeId = 4,
                            PValueId = 22
                        },
                        new
                        {
                            Id = 23,
                            PAttributeId = 4,
                            PValueId = 23
                        },
                        new
                        {
                            Id = 24,
                            PAttributeId = 4,
                            PValueId = 24
                        },
                        new
                        {
                            Id = 25,
                            PAttributeId = 4,
                            PValueId = 25
                        },
                        new
                        {
                            Id = 26,
                            PAttributeId = 4,
                            PValueId = 26
                        },
                        new
                        {
                            Id = 27,
                            PAttributeId = 4,
                            PValueId = 27
                        },
                        new
                        {
                            Id = 28,
                            PAttributeId = 4,
                            PValueId = 28
                        },
                        new
                        {
                            Id = 29,
                            PAttributeId = 5,
                            PValueId = 29
                        },
                        new
                        {
                            Id = 30,
                            PAttributeId = 5,
                            PValueId = 30
                        },
                        new
                        {
                            Id = 31,
                            PAttributeId = 5,
                            PValueId = 31
                        },
                        new
                        {
                            Id = 32,
                            PAttributeId = 5,
                            PValueId = 32
                        },
                        new
                        {
                            Id = 33,
                            PAttributeId = 5,
                            PValueId = 33
                        },
                        new
                        {
                            Id = 34,
                            PAttributeId = 5,
                            PValueId = 34
                        },
                        new
                        {
                            Id = 35,
                            PAttributeId = 5,
                            PValueId = 35
                        },
                        new
                        {
                            Id = 36,
                            PAttributeId = 5,
                            PValueId = 36
                        },
                        new
                        {
                            Id = 37,
                            PAttributeId = 5,
                            PValueId = 37
                        },
                        new
                        {
                            Id = 38,
                            PAttributeId = 5,
                            PValueId = 38
                        },
                        new
                        {
                            Id = 39,
                            PAttributeId = 5,
                            PValueId = 39
                        },
                        new
                        {
                            Id = 40,
                            PAttributeId = 5,
                            PValueId = 40
                        },
                        new
                        {
                            Id = 41,
                            PAttributeId = 5,
                            PValueId = 41
                        },
                        new
                        {
                            Id = 42,
                            PAttributeId = 6,
                            PValueId = 42
                        },
                        new
                        {
                            Id = 43,
                            PAttributeId = 6,
                            PValueId = 43
                        },
                        new
                        {
                            Id = 44,
                            PAttributeId = 6,
                            PValueId = 44
                        },
                        new
                        {
                            Id = 45,
                            PAttributeId = 6,
                            PValueId = 45
                        },
                        new
                        {
                            Id = 46,
                            PAttributeId = 6,
                            PValueId = 46
                        },
                        new
                        {
                            Id = 47,
                            PAttributeId = 6,
                            PValueId = 47
                        },
                        new
                        {
                            Id = 48,
                            PAttributeId = 6,
                            PValueId = 48
                        },
                        new
                        {
                            Id = 49,
                            PAttributeId = 6,
                            PValueId = 49
                        },
                        new
                        {
                            Id = 50,
                            PAttributeId = 6,
                            PValueId = 50
                        },
                        new
                        {
                            Id = 51,
                            PAttributeId = 6,
                            PValueId = 51
                        },
                        new
                        {
                            Id = 52,
                            PAttributeId = 6,
                            PValueId = 52
                        },
                        new
                        {
                            Id = 53,
                            PAttributeId = 6,
                            PValueId = 53
                        },
                        new
                        {
                            Id = 54,
                            PAttributeId = 6,
                            PValueId = 54
                        },
                        new
                        {
                            Id = 55,
                            PAttributeId = 6,
                            PValueId = 55
                        },
                        new
                        {
                            Id = 56,
                            PAttributeId = 6,
                            PValueId = 56
                        },
                        new
                        {
                            Id = 57,
                            PAttributeId = 7,
                            PValueId = 57
                        },
                        new
                        {
                            Id = 58,
                            PAttributeId = 7,
                            PValueId = 58
                        },
                        new
                        {
                            Id = 59,
                            PAttributeId = 7,
                            PValueId = 59
                        },
                        new
                        {
                            Id = 60,
                            PAttributeId = 7,
                            PValueId = 60
                        },
                        new
                        {
                            Id = 61,
                            PAttributeId = 8,
                            PValueId = 61
                        },
                        new
                        {
                            Id = 62,
                            PAttributeId = 8,
                            PValueId = 62
                        },
                        new
                        {
                            Id = 63,
                            PAttributeId = 8,
                            PValueId = 63
                        },
                        new
                        {
                            Id = 64,
                            PAttributeId = 8,
                            PValueId = 64
                        },
                        new
                        {
                            Id = 65,
                            PAttributeId = 8,
                            PValueId = 65
                        },
                        new
                        {
                            Id = 66,
                            PAttributeId = 9,
                            PValueId = 66
                        },
                        new
                        {
                            Id = 67,
                            PAttributeId = 9,
                            PValueId = 67
                        },
                        new
                        {
                            Id = 68,
                            PAttributeId = 10,
                            PValueId = 68
                        },
                        new
                        {
                            Id = 69,
                            PAttributeId = 10,
                            PValueId = 69
                        },
                        new
                        {
                            Id = 70,
                            PAttributeId = 10,
                            PValueId = 70
                        },
                        new
                        {
                            Id = 71,
                            PAttributeId = 10,
                            PValueId = 71
                        },
                        new
                        {
                            Id = 72,
                            PAttributeId = 10,
                            PValueId = 72
                        },
                        new
                        {
                            Id = 73,
                            PAttributeId = 10,
                            PValueId = 73
                        },
                        new
                        {
                            Id = 74,
                            PAttributeId = 10,
                            PValueId = 74
                        },
                        new
                        {
                            Id = 75,
                            PAttributeId = 11,
                            PValueId = 75
                        },
                        new
                        {
                            Id = 76,
                            PAttributeId = 11,
                            PValueId = 76
                        },
                        new
                        {
                            Id = 77,
                            PAttributeId = 11,
                            PValueId = 77
                        });
                });

            modelBuilder.Entity("TechShop.Models.PAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PAttribute");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HDD Size"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SSD Size"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Display Size"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Display Resolution"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Processor Type"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Number of CPU Cores"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Operating System"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Graphics Type"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Graphics Processor"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Graphics Brand"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PFilterNameId")
                        .HasColumnType("int");

                    b.Property<int>("PFilterValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PFilterValueId");

                    b.HasIndex("PFilterNameId", "PFilterValueId")
                        .IsUnique();

                    b.ToTable("PFilter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PFilterNameId = 1,
                            PFilterValueId = 1
                        },
                        new
                        {
                            Id = 2,
                            PFilterNameId = 1,
                            PFilterValueId = 2
                        },
                        new
                        {
                            Id = 3,
                            PFilterNameId = 1,
                            PFilterValueId = 3
                        },
                        new
                        {
                            Id = 4,
                            PFilterNameId = 1,
                            PFilterValueId = 4
                        },
                        new
                        {
                            Id = 5,
                            PFilterNameId = 1,
                            PFilterValueId = 5
                        },
                        new
                        {
                            Id = 6,
                            PFilterNameId = 1,
                            PFilterValueId = 6
                        },
                        new
                        {
                            Id = 7,
                            PFilterNameId = 2,
                            PFilterValueId = 7
                        },
                        new
                        {
                            Id = 8,
                            PFilterNameId = 2,
                            PFilterValueId = 8
                        },
                        new
                        {
                            Id = 9,
                            PFilterNameId = 2,
                            PFilterValueId = 9
                        },
                        new
                        {
                            Id = 10,
                            PFilterNameId = 3,
                            PFilterValueId = 10
                        },
                        new
                        {
                            Id = 11,
                            PFilterNameId = 3,
                            PFilterValueId = 11
                        },
                        new
                        {
                            Id = 12,
                            PFilterNameId = 3,
                            PFilterValueId = 12
                        });
                });

            modelBuilder.Entity("TechShop.Models.PFilterName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("FilterName")
                        .IsUnique();

                    b.ToTable("PFilterName");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilterName = "RAM Size"
                        },
                        new
                        {
                            Id = 2,
                            FilterName = "SSD size"
                        },
                        new
                        {
                            Id = 3,
                            FilterName = "Operating System"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PFilterPAVPair", b =>
                {
                    b.Property<int>("PFilterId")
                        .HasColumnType("int");

                    b.Property<int>("PAVPairId")
                        .HasColumnType("int");

                    b.HasKey("PFilterId", "PAVPairId");

                    b.HasIndex("PAVPairId");

                    b.ToTable("PFilterPAVPair");

                    b.HasData(
                        new
                        {
                            PFilterId = 1,
                            PAVPairId = 1
                        },
                        new
                        {
                            PFilterId = 2,
                            PAVPairId = 2
                        },
                        new
                        {
                            PFilterId = 3,
                            PAVPairId = 3
                        },
                        new
                        {
                            PFilterId = 4,
                            PAVPairId = 4
                        },
                        new
                        {
                            PFilterId = 5,
                            PAVPairId = 5
                        },
                        new
                        {
                            PFilterId = 6,
                            PAVPairId = 6
                        },
                        new
                        {
                            PFilterId = 7,
                            PAVPairId = 16
                        },
                        new
                        {
                            PFilterId = 7,
                            PAVPairId = 17
                        },
                        new
                        {
                            PFilterId = 7,
                            PAVPairId = 18
                        },
                        new
                        {
                            PFilterId = 8,
                            PAVPairId = 19
                        },
                        new
                        {
                            PFilterId = 9,
                            PAVPairId = 20
                        },
                        new
                        {
                            PFilterId = 10,
                            PAVPairId = 61
                        },
                        new
                        {
                            PFilterId = 10,
                            PAVPairId = 62
                        },
                        new
                        {
                            PFilterId = 11,
                            PAVPairId = 65
                        },
                        new
                        {
                            PFilterId = 12,
                            PAVPairId = 63
                        });
                });

            modelBuilder.Entity("TechShop.Models.PFilterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("FilterValue")
                        .IsUnique();

                    b.ToTable("PFilterValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilterValue = "2 GB"
                        },
                        new
                        {
                            Id = 2,
                            FilterValue = "4 GB"
                        },
                        new
                        {
                            Id = 3,
                            FilterValue = "6 GB"
                        },
                        new
                        {
                            Id = 4,
                            FilterValue = "8 GB"
                        },
                        new
                        {
                            Id = 5,
                            FilterValue = "12 GB"
                        },
                        new
                        {
                            Id = 6,
                            FilterValue = "16 GB"
                        },
                        new
                        {
                            Id = 7,
                            FilterValue = "128 to 256 GB"
                        },
                        new
                        {
                            Id = 8,
                            FilterValue = "257 to 512 GB"
                        },
                        new
                        {
                            Id = 9,
                            FilterValue = "513 to 1024 GB"
                        },
                        new
                        {
                            Id = 10,
                            FilterValue = "Windows"
                        },
                        new
                        {
                            Id = 11,
                            FilterValue = "MacOS"
                        },
                        new
                        {
                            Id = 12,
                            FilterValue = "Unix"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "2 GB"
                        },
                        new
                        {
                            Id = 2,
                            Value = "4 GB"
                        },
                        new
                        {
                            Id = 3,
                            Value = "6 GB"
                        },
                        new
                        {
                            Id = 4,
                            Value = "8 GB"
                        },
                        new
                        {
                            Id = 5,
                            Value = "12 GB"
                        },
                        new
                        {
                            Id = 6,
                            Value = "16 GB"
                        },
                        new
                        {
                            Id = 7,
                            Value = "24 GB"
                        },
                        new
                        {
                            Id = 8,
                            Value = "32 GB"
                        },
                        new
                        {
                            Id = 9,
                            Value = "64 GB"
                        },
                        new
                        {
                            Id = 10,
                            Value = "None"
                        },
                        new
                        {
                            Id = 11,
                            Value = "500 GB"
                        },
                        new
                        {
                            Id = 12,
                            Value = "1000 GB"
                        },
                        new
                        {
                            Id = 13,
                            Value = "1500 GB"
                        },
                        new
                        {
                            Id = 14,
                            Value = "2000 GB"
                        },
                        new
                        {
                            Id = 15,
                            Value = "2500 GB"
                        },
                        new
                        {
                            Id = 16,
                            Value = "128 GB"
                        },
                        new
                        {
                            Id = 17,
                            Value = "180 GB"
                        },
                        new
                        {
                            Id = 18,
                            Value = "256 GB"
                        },
                        new
                        {
                            Id = 19,
                            Value = "512 GB"
                        },
                        new
                        {
                            Id = 20,
                            Value = "1024 GB"
                        },
                        new
                        {
                            Id = 21,
                            Value = "11\""
                        },
                        new
                        {
                            Id = 22,
                            Value = "11.6\""
                        },
                        new
                        {
                            Id = 23,
                            Value = "12\""
                        },
                        new
                        {
                            Id = 24,
                            Value = "12.5\""
                        },
                        new
                        {
                            Id = 25,
                            Value = "13.3\""
                        },
                        new
                        {
                            Id = 26,
                            Value = "14\""
                        },
                        new
                        {
                            Id = 27,
                            Value = "15.6\""
                        },
                        new
                        {
                            Id = 28,
                            Value = "17.3\""
                        },
                        new
                        {
                            Id = 29,
                            Value = "1366x768"
                        },
                        new
                        {
                            Id = 30,
                            Value = "1366x912"
                        },
                        new
                        {
                            Id = 31,
                            Value = "1440x900"
                        },
                        new
                        {
                            Id = 32,
                            Value = "1600x900"
                        },
                        new
                        {
                            Id = 33,
                            Value = "1920x1080"
                        },
                        new
                        {
                            Id = 34,
                            Value = "2160x1440"
                        },
                        new
                        {
                            Id = 35,
                            Value = "2304x1440"
                        },
                        new
                        {
                            Id = 36,
                            Value = "2560x1600"
                        },
                        new
                        {
                            Id = 37,
                            Value = "2880x1800"
                        },
                        new
                        {
                            Id = 38,
                            Value = "3000x2000"
                        },
                        new
                        {
                            Id = 39,
                            Value = "3072x1920"
                        },
                        new
                        {
                            Id = 40,
                            Value = "3200x1800"
                        },
                        new
                        {
                            Id = 41,
                            Value = "3840x2160"
                        },
                        new
                        {
                            Id = 42,
                            Value = "Intel Core i9"
                        },
                        new
                        {
                            Id = 43,
                            Value = "Intel Core i7"
                        },
                        new
                        {
                            Id = 44,
                            Value = "Intel Core i5"
                        },
                        new
                        {
                            Id = 45,
                            Value = "Intel Core i3"
                        },
                        new
                        {
                            Id = 46,
                            Value = "Intel Xeon"
                        },
                        new
                        {
                            Id = 47,
                            Value = "Intel Core M7"
                        },
                        new
                        {
                            Id = 48,
                            Value = "Intel Core M5"
                        },
                        new
                        {
                            Id = 49,
                            Value = "Intel Core M3"
                        },
                        new
                        {
                            Id = 50,
                            Value = "Intel Pentium"
                        },
                        new
                        {
                            Id = 51,
                            Value = "Intel Celeron"
                        },
                        new
                        {
                            Id = 52,
                            Value = "Intel Atom"
                        },
                        new
                        {
                            Id = 53,
                            Value = "AMD Razen 7"
                        },
                        new
                        {
                            Id = 54,
                            Value = "AMD Razen 5"
                        },
                        new
                        {
                            Id = 55,
                            Value = "AMD Razen 3"
                        },
                        new
                        {
                            Id = 56,
                            Value = "AMD A9"
                        },
                        new
                        {
                            Id = 57,
                            Value = "2"
                        },
                        new
                        {
                            Id = 58,
                            Value = "4"
                        },
                        new
                        {
                            Id = 59,
                            Value = "6"
                        },
                        new
                        {
                            Id = 60,
                            Value = "8"
                        },
                        new
                        {
                            Id = 61,
                            Value = "Windows 10 Home"
                        },
                        new
                        {
                            Id = 62,
                            Value = "Windows 10 Professional"
                        },
                        new
                        {
                            Id = 63,
                            Value = "UNIX"
                        },
                        new
                        {
                            Id = 64,
                            Value = "Chrome OS"
                        },
                        new
                        {
                            Id = 65,
                            Value = "MacOS"
                        },
                        new
                        {
                            Id = 66,
                            Value = "Integrated"
                        },
                        new
                        {
                            Id = 67,
                            Value = "Dedicated & Integrated"
                        },
                        new
                        {
                            Id = 68,
                            Value = "GeForce RTX 2080"
                        },
                        new
                        {
                            Id = 69,
                            Value = "GeForce RTX 2080 MaxQ"
                        },
                        new
                        {
                            Id = 70,
                            Value = "GeForce RTX 2070"
                        },
                        new
                        {
                            Id = 71,
                            Value = "GeForce RTX 2070 MaxQ"
                        },
                        new
                        {
                            Id = 72,
                            Value = "Radeon 540X"
                        },
                        new
                        {
                            Id = 73,
                            Value = "GeForce MX250"
                        },
                        new
                        {
                            Id = 74,
                            Value = "GeForce MX230"
                        },
                        new
                        {
                            Id = 75,
                            Value = "AMD"
                        },
                        new
                        {
                            Id = 76,
                            Value = "Intel"
                        },
                        new
                        {
                            Id = 77,
                            Value = "nVidia"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 1,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 2,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 3,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 4,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 5,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 6,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 7,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 8,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Initial",
                            Price = 150m,
                            ProductId = 9,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Purchase price increased",
                            Price = 167m,
                            ProductId = 1,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Description = "Purchase price increased",
                            Price = 165m,
                            ProductId = 2,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Description = "Purchase price increased",
                            Price = 193m,
                            ProductId = 3,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Description = "Purchase price increased",
                            Price = 169m,
                            ProductId = 4,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Description = "Purchase price increased",
                            Price = 156m,
                            ProductId = 5,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Description = "Purchase price increased",
                            Price = 176m,
                            ProductId = 6,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Description = "Purchase price increased",
                            Price = 181m,
                            ProductId = 7,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Description = "Purchase price increased",
                            Price = 173m,
                            ProductId = 8,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Description = "Purchase price increased",
                            Price = 165m,
                            ProductId = 9,
                            StartDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(1,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 128 GB, Windows 10 Home]",
                            Img = "/img/product01.png",
                            Name = "Laptop ASUS Air G3425",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 6,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 128 GB, Windows 10 Home]",
                            Img = "/img/product01.png",
                            Name = "Laptop Lenovo C1124",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            Description = "[i5, 1.8/8Gb/128SSD, (MQD32RU/A)]",
                            Img = "/img/product03.png",
                            Name = "Laptop Mackbook Air 2",
                            Rating = 3m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 8,
                            Description = "[1920x1200, IPS, 8х2.36 GGz, 3 GB, BT, GPS, 5100 mAh, Android 8.x+]",
                            Img = "/img/product04.png",
                            Name = "Tablet Sony Z3",
                            Rating = 4m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 7,
                            Description = "[5.1, Closed-Back, 20 Gz - 25000 Gz, 35Ω, wired, cable - 2 m, black]",
                            Img = "/img/product05.png",
                            Name = "Headphones Epson GT23",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 128 GB, Windows 10 Professional]",
                            Img = "/img/product06.png",
                            Name = "Laptop Acer H2451",
                            Rating = 4m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 6 GB DDR3, SSD 128 GB, Windows 10 Professional]",
                            Img = "/img/product07.png",
                            Name = "Laptop ASUS Air G3425",
                            Rating = 1m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x4000 MGz, 8 GB DDR3, SSD 128 GB, Windows 10 Professional]",
                            Img = "/img/product08.png",
                            Name = "Laptop ASUS Air G5161",
                            Rating = 2m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 16 GB DDR3, SSD 512 GB, Windows 10 Professional]",
                            Img = "/img/product09.png",
                            Name = "Laptop ASUS Air G9515",
                            Rating = 3m
                        });
                });

            modelBuilder.Entity("TechShop.Models.ProductDiscount", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("ProductDiscount");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            DiscountId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            DiscountId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 6,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            DiscountId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            DiscountId = 3
                        });
                });

            modelBuilder.Entity("TechShop.Models.ProductPAVPair", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PAVPairId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "PAVPairId");

                    b.HasIndex("PAVPairId");

                    b.ToTable("ProductPAVPair");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PAVPairId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            PAVPairId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            PAVPairId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            PAVPairId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            PAVPairId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            PAVPairId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            PAVPairId = 6
                        },
                        new
                        {
                            ProductId = 1,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 2,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 3,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 6,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 7,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 8,
                            PAVPairId = 16
                        },
                        new
                        {
                            ProductId = 9,
                            PAVPairId = 19
                        },
                        new
                        {
                            ProductId = 1,
                            PAVPairId = 61
                        },
                        new
                        {
                            ProductId = 2,
                            PAVPairId = 61
                        },
                        new
                        {
                            ProductId = 3,
                            PAVPairId = 65
                        },
                        new
                        {
                            ProductId = 6,
                            PAVPairId = 62
                        },
                        new
                        {
                            ProductId = 7,
                            PAVPairId = 62
                        },
                        new
                        {
                            ProductId = 8,
                            PAVPairId = 62
                        },
                        new
                        {
                            ProductId = 9,
                            PAVPairId = 62
                        });
                });

            modelBuilder.Entity("TechShop.Models.Category", b =>
                {
                    b.HasOne("TechShop.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.HasOne("TechShop.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PAVPair", b =>
                {
                    b.HasOne("TechShop.Models.PAttribute", "PAttribute")
                        .WithMany()
                        .HasForeignKey("PAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.PValue", "PValue")
                        .WithMany()
                        .HasForeignKey("PValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PFilter", b =>
                {
                    b.HasOne("TechShop.Models.PFilterName", "PFilterName")
                        .WithMany()
                        .HasForeignKey("PFilterNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.PFilterValue", "PFilterValue")
                        .WithMany()
                        .HasForeignKey("PFilterValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PFilterPAVPair", b =>
                {
                    b.HasOne("TechShop.Models.PAVPair", "PAVPair")
                        .WithMany()
                        .HasForeignKey("PAVPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.PFilter", "PFilter")
                        .WithMany()
                        .HasForeignKey("PFilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.HasOne("TechShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.ProductDiscount", b =>
                {
                    b.HasOne("TechShop.Models.Discount", "Discount")
                        .WithMany("ProductDiscount")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany("ProductDiscount")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.ProductPAVPair", b =>
                {
                    b.HasOne("TechShop.Models.PAVPair", "PAVPair")
                        .WithMany()
                        .HasForeignKey("PAVPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
