// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShop.Data;

namespace TechShop.Migrations
{
    [DbContext(typeof(TechDbContext))]
    [Migration("20200316095617_CreatePFilterPAVPairTable")]
    partial class CreatePFilterPAVPairTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechShop.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Epson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("TechShop.Models.Breadcrumb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breadcrumb");
                });

            modelBuilder.Entity("TechShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Lft")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Rgt")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 0,
                            Lft = 1,
                            Name = "Categories",
                            ParentId = 0,
                            Rgt = 38,
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Lft = 2,
                            Name = "Computers and laptops",
                            ParentId = 1,
                            Rgt = 7,
                            Url = "computers-and-laptops"
                        },
                        new
                        {
                            Id = 3,
                            Level = 2,
                            Lft = 3,
                            Name = "Laptops",
                            ParentId = 2,
                            Rgt = 6,
                            Url = "laptops"
                        },
                        new
                        {
                            Id = 4,
                            Level = 3,
                            Lft = 4,
                            Name = "All Laptops",
                            ParentId = 3,
                            Rgt = 5,
                            Url = "all-laptops"
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Lft = 8,
                            Name = "Photo and video",
                            ParentId = 1,
                            Rgt = 17,
                            Url = "photo-and-video"
                        },
                        new
                        {
                            Id = 6,
                            Level = 2,
                            Lft = 9,
                            Name = "Cameras",
                            ParentId = 5,
                            Rgt = 10,
                            Url = "cameras"
                        },
                        new
                        {
                            Id = 7,
                            Level = 2,
                            Lft = 11,
                            Name = "Lenses, optics, flashes",
                            ParentId = 5,
                            Rgt = 16,
                            Url = "lenses-optics-flashes"
                        },
                        new
                        {
                            Id = 8,
                            Level = 3,
                            Lft = 12,
                            Name = "Lenses",
                            ParentId = 7,
                            Rgt = 15,
                            Url = "lenses"
                        },
                        new
                        {
                            Id = 9,
                            Level = 1,
                            Lft = 18,
                            Name = "TVs, audio, video",
                            ParentId = 1,
                            Rgt = 27,
                            Url = "tvs-audio-video"
                        },
                        new
                        {
                            Id = 10,
                            Level = 2,
                            Lft = 19,
                            Name = "TVs",
                            ParentId = 9,
                            Rgt = 26,
                            Url = "tvs"
                        },
                        new
                        {
                            Id = 11,
                            Level = 3,
                            Lft = 20,
                            Name = "All TVs",
                            ParentId = 10,
                            Rgt = 21,
                            Url = "all-tvs"
                        },
                        new
                        {
                            Id = 12,
                            Level = 3,
                            Lft = 22,
                            Name = "Smart-TVs",
                            ParentId = 10,
                            Rgt = 23,
                            Url = "smart-tvs"
                        },
                        new
                        {
                            Id = 13,
                            Level = 3,
                            Lft = 24,
                            Name = "OLED TVs",
                            ParentId = 10,
                            Rgt = 25,
                            Url = "oled-tvs"
                        },
                        new
                        {
                            Id = 14,
                            Level = 1,
                            Lft = 28,
                            Name = "Smartphones and gadgets",
                            ParentId = 1,
                            Rgt = 37,
                            Url = "smartphones-and-gadgets"
                        },
                        new
                        {
                            Id = 15,
                            Level = 2,
                            Lft = 29,
                            Name = "Smartphones",
                            ParentId = 14,
                            Rgt = 32,
                            Url = "smartphones"
                        },
                        new
                        {
                            Id = 16,
                            Level = 3,
                            Lft = 30,
                            Name = "All Smartphones",
                            ParentId = 15,
                            Rgt = 31,
                            Url = "all-smartphones"
                        },
                        new
                        {
                            Id = 17,
                            Level = 2,
                            Lft = 33,
                            Name = "Tablets",
                            ParentId = 14,
                            Rgt = 36,
                            Url = "tablets"
                        },
                        new
                        {
                            Id = 18,
                            Level = 3,
                            Lft = 34,
                            Name = "All Tablets",
                            ParentId = 17,
                            Rgt = 35,
                            Url = "all-tablets"
                        });
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoryId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 18,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("TechShop.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("TechShop.Models.PAVPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("PAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("PValueId")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PAttributeId");

                    b.HasIndex("PValueId");

                    b.ToTable("PAVPair");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 1,
                            ValueId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 1,
                            ValueId = 2
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 1,
                            ValueId = 3
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 1,
                            ValueId = 4
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 1,
                            ValueId = 5
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 1,
                            ValueId = 6
                        },
                        new
                        {
                            Id = 7,
                            AttributeId = 1,
                            ValueId = 7
                        },
                        new
                        {
                            Id = 8,
                            AttributeId = 1,
                            ValueId = 8
                        },
                        new
                        {
                            Id = 9,
                            AttributeId = 1,
                            ValueId = 9
                        },
                        new
                        {
                            Id = 10,
                            AttributeId = 2,
                            ValueId = 10
                        },
                        new
                        {
                            Id = 11,
                            AttributeId = 2,
                            ValueId = 11
                        },
                        new
                        {
                            Id = 12,
                            AttributeId = 2,
                            ValueId = 12
                        },
                        new
                        {
                            Id = 13,
                            AttributeId = 2,
                            ValueId = 13
                        },
                        new
                        {
                            Id = 14,
                            AttributeId = 2,
                            ValueId = 14
                        },
                        new
                        {
                            Id = 15,
                            AttributeId = 2,
                            ValueId = 15
                        },
                        new
                        {
                            Id = 16,
                            AttributeId = 3,
                            ValueId = 16
                        },
                        new
                        {
                            Id = 17,
                            AttributeId = 3,
                            ValueId = 17
                        },
                        new
                        {
                            Id = 18,
                            AttributeId = 3,
                            ValueId = 18
                        },
                        new
                        {
                            Id = 19,
                            AttributeId = 3,
                            ValueId = 19
                        },
                        new
                        {
                            Id = 20,
                            AttributeId = 3,
                            ValueId = 20
                        },
                        new
                        {
                            Id = 21,
                            AttributeId = 4,
                            ValueId = 21
                        },
                        new
                        {
                            Id = 22,
                            AttributeId = 4,
                            ValueId = 22
                        },
                        new
                        {
                            Id = 23,
                            AttributeId = 4,
                            ValueId = 23
                        },
                        new
                        {
                            Id = 24,
                            AttributeId = 4,
                            ValueId = 24
                        },
                        new
                        {
                            Id = 25,
                            AttributeId = 4,
                            ValueId = 25
                        },
                        new
                        {
                            Id = 26,
                            AttributeId = 4,
                            ValueId = 26
                        },
                        new
                        {
                            Id = 27,
                            AttributeId = 4,
                            ValueId = 27
                        },
                        new
                        {
                            Id = 28,
                            AttributeId = 4,
                            ValueId = 28
                        },
                        new
                        {
                            Id = 29,
                            AttributeId = 5,
                            ValueId = 29
                        },
                        new
                        {
                            Id = 30,
                            AttributeId = 5,
                            ValueId = 30
                        },
                        new
                        {
                            Id = 31,
                            AttributeId = 5,
                            ValueId = 31
                        },
                        new
                        {
                            Id = 32,
                            AttributeId = 5,
                            ValueId = 32
                        },
                        new
                        {
                            Id = 33,
                            AttributeId = 5,
                            ValueId = 33
                        },
                        new
                        {
                            Id = 34,
                            AttributeId = 5,
                            ValueId = 34
                        },
                        new
                        {
                            Id = 35,
                            AttributeId = 5,
                            ValueId = 35
                        },
                        new
                        {
                            Id = 36,
                            AttributeId = 5,
                            ValueId = 36
                        },
                        new
                        {
                            Id = 37,
                            AttributeId = 5,
                            ValueId = 37
                        },
                        new
                        {
                            Id = 38,
                            AttributeId = 5,
                            ValueId = 38
                        },
                        new
                        {
                            Id = 39,
                            AttributeId = 5,
                            ValueId = 39
                        },
                        new
                        {
                            Id = 40,
                            AttributeId = 5,
                            ValueId = 40
                        },
                        new
                        {
                            Id = 41,
                            AttributeId = 5,
                            ValueId = 41
                        },
                        new
                        {
                            Id = 42,
                            AttributeId = 6,
                            ValueId = 42
                        },
                        new
                        {
                            Id = 43,
                            AttributeId = 6,
                            ValueId = 43
                        },
                        new
                        {
                            Id = 44,
                            AttributeId = 6,
                            ValueId = 44
                        },
                        new
                        {
                            Id = 45,
                            AttributeId = 6,
                            ValueId = 45
                        },
                        new
                        {
                            Id = 46,
                            AttributeId = 6,
                            ValueId = 46
                        },
                        new
                        {
                            Id = 47,
                            AttributeId = 6,
                            ValueId = 47
                        },
                        new
                        {
                            Id = 48,
                            AttributeId = 6,
                            ValueId = 48
                        },
                        new
                        {
                            Id = 49,
                            AttributeId = 6,
                            ValueId = 49
                        },
                        new
                        {
                            Id = 50,
                            AttributeId = 6,
                            ValueId = 50
                        },
                        new
                        {
                            Id = 51,
                            AttributeId = 6,
                            ValueId = 51
                        },
                        new
                        {
                            Id = 52,
                            AttributeId = 6,
                            ValueId = 52
                        },
                        new
                        {
                            Id = 53,
                            AttributeId = 6,
                            ValueId = 53
                        },
                        new
                        {
                            Id = 54,
                            AttributeId = 6,
                            ValueId = 54
                        },
                        new
                        {
                            Id = 55,
                            AttributeId = 6,
                            ValueId = 55
                        },
                        new
                        {
                            Id = 56,
                            AttributeId = 6,
                            ValueId = 56
                        },
                        new
                        {
                            Id = 57,
                            AttributeId = 7,
                            ValueId = 57
                        },
                        new
                        {
                            Id = 58,
                            AttributeId = 7,
                            ValueId = 58
                        },
                        new
                        {
                            Id = 59,
                            AttributeId = 7,
                            ValueId = 59
                        },
                        new
                        {
                            Id = 60,
                            AttributeId = 7,
                            ValueId = 60
                        },
                        new
                        {
                            Id = 61,
                            AttributeId = 8,
                            ValueId = 61
                        },
                        new
                        {
                            Id = 62,
                            AttributeId = 8,
                            ValueId = 62
                        },
                        new
                        {
                            Id = 63,
                            AttributeId = 8,
                            ValueId = 63
                        },
                        new
                        {
                            Id = 64,
                            AttributeId = 8,
                            ValueId = 64
                        },
                        new
                        {
                            Id = 65,
                            AttributeId = 8,
                            ValueId = 65
                        },
                        new
                        {
                            Id = 66,
                            AttributeId = 9,
                            ValueId = 66
                        },
                        new
                        {
                            Id = 67,
                            AttributeId = 9,
                            ValueId = 67
                        },
                        new
                        {
                            Id = 68,
                            AttributeId = 10,
                            ValueId = 68
                        },
                        new
                        {
                            Id = 69,
                            AttributeId = 10,
                            ValueId = 69
                        },
                        new
                        {
                            Id = 70,
                            AttributeId = 10,
                            ValueId = 70
                        },
                        new
                        {
                            Id = 71,
                            AttributeId = 10,
                            ValueId = 71
                        },
                        new
                        {
                            Id = 72,
                            AttributeId = 10,
                            ValueId = 72
                        },
                        new
                        {
                            Id = 73,
                            AttributeId = 10,
                            ValueId = 73
                        },
                        new
                        {
                            Id = 74,
                            AttributeId = 10,
                            ValueId = 74
                        },
                        new
                        {
                            Id = 75,
                            AttributeId = 11,
                            ValueId = 75
                        },
                        new
                        {
                            Id = 76,
                            AttributeId = 11,
                            ValueId = 76
                        },
                        new
                        {
                            Id = 77,
                            AttributeId = 11,
                            ValueId = 77
                        });
                });

            modelBuilder.Entity("TechShop.Models.PAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("PAttribute");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HDD Size"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SSD Size"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Display Size"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Display Resolution"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Processor Type"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Number of CPU Cores"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Operating System"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Graphics Type"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Graphics Processor"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Graphics Brand"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("PValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "2 GB"
                        },
                        new
                        {
                            Id = 2,
                            Value = "4 GB"
                        },
                        new
                        {
                            Id = 3,
                            Value = "6 GB"
                        },
                        new
                        {
                            Id = 4,
                            Value = "8 GB"
                        },
                        new
                        {
                            Id = 5,
                            Value = "12 GB"
                        },
                        new
                        {
                            Id = 6,
                            Value = "16 GB"
                        },
                        new
                        {
                            Id = 7,
                            Value = "24 GB"
                        },
                        new
                        {
                            Id = 8,
                            Value = "32 GB"
                        },
                        new
                        {
                            Id = 9,
                            Value = "64 GB"
                        },
                        new
                        {
                            Id = 10,
                            Value = "None"
                        },
                        new
                        {
                            Id = 11,
                            Value = "500 GB"
                        },
                        new
                        {
                            Id = 12,
                            Value = "1000 GB"
                        },
                        new
                        {
                            Id = 13,
                            Value = "1500 GB"
                        },
                        new
                        {
                            Id = 14,
                            Value = "2000 GB"
                        },
                        new
                        {
                            Id = 15,
                            Value = "2500 GB"
                        },
                        new
                        {
                            Id = 16,
                            Value = "128 GB"
                        },
                        new
                        {
                            Id = 17,
                            Value = "180 GB"
                        },
                        new
                        {
                            Id = 18,
                            Value = "256 GB"
                        },
                        new
                        {
                            Id = 19,
                            Value = "512 GB"
                        },
                        new
                        {
                            Id = 20,
                            Value = "1024 GB"
                        },
                        new
                        {
                            Id = 21,
                            Value = "11\""
                        },
                        new
                        {
                            Id = 22,
                            Value = "11.6\""
                        },
                        new
                        {
                            Id = 23,
                            Value = "12\""
                        },
                        new
                        {
                            Id = 24,
                            Value = "12.5\""
                        },
                        new
                        {
                            Id = 25,
                            Value = "13.3\""
                        },
                        new
                        {
                            Id = 26,
                            Value = "14\""
                        },
                        new
                        {
                            Id = 27,
                            Value = "15.6\""
                        },
                        new
                        {
                            Id = 28,
                            Value = "17.3\""
                        },
                        new
                        {
                            Id = 29,
                            Value = "1366x768"
                        },
                        new
                        {
                            Id = 30,
                            Value = "1366x912"
                        },
                        new
                        {
                            Id = 31,
                            Value = "1440x900"
                        },
                        new
                        {
                            Id = 32,
                            Value = "1600x900"
                        },
                        new
                        {
                            Id = 33,
                            Value = "1920x1080"
                        },
                        new
                        {
                            Id = 34,
                            Value = "2160x1440"
                        },
                        new
                        {
                            Id = 35,
                            Value = "2304x1440"
                        },
                        new
                        {
                            Id = 36,
                            Value = "2560x1600"
                        },
                        new
                        {
                            Id = 37,
                            Value = "2880x1800"
                        },
                        new
                        {
                            Id = 38,
                            Value = "3000x2000"
                        },
                        new
                        {
                            Id = 39,
                            Value = "3072x1920"
                        },
                        new
                        {
                            Id = 40,
                            Value = "3200x1800"
                        },
                        new
                        {
                            Id = 41,
                            Value = "3840x2160"
                        },
                        new
                        {
                            Id = 42,
                            Value = "Intel Core i9"
                        },
                        new
                        {
                            Id = 43,
                            Value = "Intel Core i7"
                        },
                        new
                        {
                            Id = 44,
                            Value = "Intel Core i5"
                        },
                        new
                        {
                            Id = 45,
                            Value = "Intel Core i3"
                        },
                        new
                        {
                            Id = 46,
                            Value = "Intel Xeon"
                        },
                        new
                        {
                            Id = 47,
                            Value = "Intel Core M7"
                        },
                        new
                        {
                            Id = 48,
                            Value = "Intel Core M5"
                        },
                        new
                        {
                            Id = 49,
                            Value = "Intel Core M3"
                        },
                        new
                        {
                            Id = 50,
                            Value = "Intel Pentium"
                        },
                        new
                        {
                            Id = 51,
                            Value = "Intel Celeron"
                        },
                        new
                        {
                            Id = 52,
                            Value = "Intel Atom"
                        },
                        new
                        {
                            Id = 53,
                            Value = "AMD Razen 7"
                        },
                        new
                        {
                            Id = 54,
                            Value = "AMD Razen 5"
                        },
                        new
                        {
                            Id = 55,
                            Value = "AMD Razen 3"
                        },
                        new
                        {
                            Id = 56,
                            Value = "AMD A9"
                        },
                        new
                        {
                            Id = 57,
                            Value = "2"
                        },
                        new
                        {
                            Id = 58,
                            Value = "4"
                        },
                        new
                        {
                            Id = 59,
                            Value = "6"
                        },
                        new
                        {
                            Id = 60,
                            Value = "8"
                        },
                        new
                        {
                            Id = 61,
                            Value = "Windows 10 Home"
                        },
                        new
                        {
                            Id = 62,
                            Value = "Windows 10 Professional"
                        },
                        new
                        {
                            Id = 63,
                            Value = "UNIX"
                        },
                        new
                        {
                            Id = 64,
                            Value = "Chrome OS"
                        },
                        new
                        {
                            Id = 65,
                            Value = "MacOS"
                        },
                        new
                        {
                            Id = 66,
                            Value = "Integrated"
                        },
                        new
                        {
                            Id = 67,
                            Value = "Dedicated & Integrated"
                        },
                        new
                        {
                            Id = 68,
                            Value = "GeForce RTX 2080"
                        },
                        new
                        {
                            Id = 69,
                            Value = "GeForce RTX 2080 MaxQ"
                        },
                        new
                        {
                            Id = 70,
                            Value = "GeForce RTX 2070"
                        },
                        new
                        {
                            Id = 71,
                            Value = "GeForce RTX 2070 MaxQ"
                        },
                        new
                        {
                            Id = 72,
                            Value = "Radeon 540X"
                        },
                        new
                        {
                            Id = 73,
                            Value = "GeForce MX250"
                        },
                        new
                        {
                            Id = 74,
                            Value = "GeForce MX230"
                        },
                        new
                        {
                            Id = 75,
                            Value = "AMD"
                        },
                        new
                        {
                            Id = 76,
                            Value = "Intel"
                        },
                        new
                        {
                            Id = 77,
                            Value = "nVidia"
                        });
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 120 GB, without OS]",
                            Img = "/img/product01.png",
                            Name = "Laptop ASUS Air G3425",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 6,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 120 GB, Windows 10]",
                            Img = "/img/product01.png",
                            Name = "Laptop Lenovo C1124",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            Description = "[i5, 1.8/8Gb/128SSD, (MQD32RU/A)]",
                            Img = "/img/product03.png",
                            Name = "Laptop Mackbook Air 2",
                            Rating = 3m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 8,
                            Description = "[1920x1200, IPS, 8х2.36 GGz, 3 GB, BT, GPS, 5100 mAh, Android 8.x+]",
                            Img = "/img/product04.png",
                            Name = "Tablet Sony Z3",
                            Rating = 4m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 7,
                            Description = "[5.1, Closed-Back, 20 Gz - 25000 Gz, 35Ω, wired, cable - 2 m, black]",
                            Img = "/img/product05.png",
                            Name = "Headphones Epson GT23",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 4 GB DDR3, SSD 120 GB, without OS]",
                            Img = "/img/product06.png",
                            Name = "Laptop Acer H2451",
                            Rating = 4m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 6 GB DDR3, SSD 120 GB, without OS]",
                            Img = "/img/product07.png",
                            Name = "Laptop ASUS Air G3425",
                            Rating = 1m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x4000 MGz, 8 GB DDR3, SSD 120 GB, Windows 10]",
                            Img = "/img/product08.png",
                            Name = "Laptop ASUS Air G5161",
                            Rating = 2m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Description = "[Intel Celeron J4005, 2x2000 MGz, 16 GB DDR3, SSD 1 TB, Windows 10]",
                            Img = "/img/product09.png",
                            Name = "Laptop ASUS Air G9515",
                            Rating = 3m
                        });
                });

            modelBuilder.Entity("TechShop.Models.ProductPAVPair", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AVPairId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "AVPairId");

                    b.HasIndex("AVPairId");

                    b.ToTable("ProductPAVPair");
                });

            modelBuilder.Entity("TechShop.Models.CategoryProduct", b =>
                {
                    b.HasOne("TechShop.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.Discount", b =>
                {
                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.PAVPair", b =>
                {
                    b.HasOne("TechShop.Models.PAttribute", "PAttribute")
                        .WithMany()
                        .HasForeignKey("PAttributeId");

                    b.HasOne("TechShop.Models.PValue", "PValue")
                        .WithMany()
                        .HasForeignKey("PValueId");
                });

            modelBuilder.Entity("TechShop.Models.PriceHistory", b =>
                {
                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.Product", b =>
                {
                    b.HasOne("TechShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechShop.Models.ProductPAVPair", b =>
                {
                    b.HasOne("TechShop.Models.PAVPair", "PAVPair")
                        .WithMany()
                        .HasForeignKey("AVPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
